export const LEVEL7DATA = [
    {
        "name": "background",
        "tileset": "tiles",
        "data": [
            38,
            -1,
            40,
            38,
            -1,
            -1,
            30,
            -1,
            40,
            48,
            40,
            40,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            39,
            40,
            50,
            51,
            31,
            43,
            -1,
            -1,
            39,
            32,
            43,
            -1,
            45,
            46,
            56,
            57,
            43,
            -1,
            32,
            37,
            45,
            46,
            -1,
            32,
            46,
            39,
            40,
            -1,
            -1,
            -1,
            42,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            45,
            46,
            -1,
            0,
            1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            6,
            7,
            0,
            16,
            1,
            4,
            16,
            16,
            10,
            10,
            15,
            2,
            20,
            20,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            21,
            20,
            12,
            13,
            13,
            13,
            13,
            13,
            13,
            12,
            13,
            13,
            13,
            14,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
        ]
    },
    {
        "name": "collision",
        "entities": [
            {
                "name": "platform",
                "id": 0,
                "x": 0,
                "y": 56,
                "width": 96,
                "height": 8
            },
            {
                "name": "platform",
                "id": 1,
                "x": -8,
                "y": 0,
                "width": 8,
                "height": 72
            },
            {
                "name": "platform",
                "id": 2,
                "x": 104,
                "y": 0,
                "width": 8,
                "height": 72
            },
            {
                "name": "platform",
                "id": 4,
                "x": 80,
                "y": 40,
                "width": 24,
                "height": 24
            }
        ]
    },
    {
        "name": "entities",
        "entities": [
            {
                "name": "triggerEnemy",
                "id": 2,
                "x": 40,
                "y": 32,
                "width": 8,
                "height": 24,
                "nodes": [
                    {
                        "x": 56,
                        "y": 48
                    }
                ]
            },
            {
                "name": "enemy_mojo",
                "id": 3,
                "x": 56,
                "y": 48,
                "values": {
                    "flipH": -1,
                    "state": "rise",
                    "triggered": true
                }
            },
            {
                "name": "door",
                "id": 5,
                "x": 96,
                "y": 16,
                "width": 8,
                "height": 32
            },
            {
                "name": "enemy_thor",
                "id": 6,
                "x": 64,
                "y": 48,
                "values": {
                    "flipH": -1,
                    "state": "run",
                    "triggered": false
                }
            },
            {
                "name": "enemy_ryan",
                "id": 7,
                "x": 88,
                "y": 32,
                "values": {
                    "flipH": -1,
                    "state": "rise",
                    "triggered": true
                }
            },
            {
                "name": "triggerEnemy",
                "id": 9,
                "x": 24,
                "y": 32,
                "width": 8,
                "height": 24,
                "nodes": [
                    {
                        "x": 88,
                        "y": 32
                    }
                ]
            },
            {
                "name": "player",
                "id": 10,
                "x": 0,
                "y": 48
            },
            {
                "name": "hideEnemy",
                "id": 11,
                "x": 8,
                "y": 48,
                "width": 8,
                "height": 8
            },
            {
                "name": "apple_item",
                "id": 12,
                "x": 80,
                "y": 24,
                "width": 8,
                "height": 8
            }
        ]
    }
];