export const LEVEL3DATA = [
    {
        "name": "background",
        "tileset": "tiles",
        "data": [
            -1,
            42,
            -1,
            44,
            -1,
            -1,
            -1,
            40,
            41,
            32,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            43,
            -1,
            46,
            47,
            50,
            51,
            40,
            46,
            47,
            -1,
            30,
            -1,
            -1,
            -1,
            43,
            44,
            56,
            57,
            49,
            36,
            31,
            41,
            -1,
            38,
            -1,
            -1,
            -1,
            40,
            41,
            -1,
            32,
            -1,
            46,
            47,
            -1,
            -1,
            -1,
            -1,
            -1,
            46,
            47,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            0,
            15,
            1,
            4,
            18,
            19,
            -1,
            -1,
            1,
            1,
            1,
            5,
            7,
            7,
            7,
            8,
            24,
            25,
            6,
            7,
            7,
            7,
            7,
            7,
            12,
            13,
            13,
            14,
            12,
            13,
            14,
            14,
            13,
            13,
            12,
            12,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
        ]
    },
    {
        "name": "collision",
        "entities": [
            {
                "name": "platform",
                "id": 0,
                "x": 0,
                "y": 56,
                "width": 32,
                "height": 8
            },
            {
                "name": "platform",
                "id": 1,
                "x": -8,
                "y": 0,
                "width": 8,
                "height": 72
            },
            {
                "name": "platform",
                "id": 2,
                "x": 96,
                "y": 0,
                "width": 8,
                "height": 72
            },
            {
                "name": "platform",
                "id": 3,
                "x": 48,
                "y": 56,
                "width": 56,
                "height": 8
            }
        ]
    },
    {
        "name": "entities",
        "entities": [
            {
                "name": "player",
                "id": 1,
                "x": 0,
                "y": 48
            },
            {
                "name": "hurt",
                "id": 4,
                "x": 24,
                "y": 64,
                "width": 32,
                "height": 8
            },
            {
                "name": "door",
                "id": 5,
                "x": 88,
                "y": 24,
                "width": 8,
                "height": 32
            },
            {
                "name": "apple_item",
                "id": 6,
                "x": 40,
                "y": 40,
                "width": 8,
                "height": 8
            }
        ]
    },
    {
        "name": "texts",
        "entities": [
            {
                "name": "text",
                "id": 0,
                "x": 0,
                "y": 80,
                "width": 8,
                "height": 8,
                "values": {
                    "text": "Press 'z' to Jump",
                    "name": "jump"
                }
            }
        ]
    }
];