export const LEVEL4DATA = [
    {
        "name": "background",
        "tileset": "tiles",
        "data": [
            36,
            -1,
            36,
            -1,
            -1,
            48,
            49,
            36,
            32,
            -1,
            -1,
            47,
            -1,
            -1,
            48,
            -1,
            -1,
            54,
            -1,
            40,
            41,
            50,
            51,
            54,
            -1,
            -1,
            30,
            55,
            -1,
            32,
            36,
            46,
            47,
            56,
            57,
            54,
            42,
            48,
            49,
            42,
            43,
            -1,
            42,
            54,
            40,
            41,
            31,
            43,
            -1,
            54,
            55,
            -1,
            -1,
            -1,
            -1,
            -1,
            46,
            47,
            43,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            11,
            -1,
            -1,
            0,
            10,
            18,
            19,
            -1,
            10,
            4,
            4,
            10,
            5,
            6,
            7,
            7,
            8,
            24,
            25,
            24,
            6,
            7,
            7,
            7,
            8,
            12,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            14,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
        ]
    },
    {
        "name": "collision",
        "entities": [
            {
                "name": "platform",
                "id": 0,
                "x": 0,
                "y": 56,
                "width": 32,
                "height": 8
            },
            {
                "name": "platform",
                "id": 1,
                "x": -8,
                "y": 0,
                "width": 8,
                "height": 72
            },
            {
                "name": "platform",
                "id": 2,
                "x": 96,
                "y": 0,
                "width": 8,
                "height": 72
            },
            {
                "name": "platform",
                "id": 3,
                "x": 56,
                "y": 56,
                "width": 48,
                "height": 8
            }
        ]
    },
    {
        "name": "entities",
        "entities": [
            {
                "name": "player",
                "id": 1,
                "x": 0,
                "y": 48
            },
            {
                "name": "door",
                "id": 5,
                "x": 88,
                "y": 24,
                "width": 8,
                "height": 32
            },
            {
                "name": "corn_item",
                "id": 7,
                "x": 40,
                "y": 40,
                "width": 8,
                "height": 8
            },
            {
                "name": "apple_item",
                "id": 8,
                "x": 72,
                "y": 48,
                "width": 8,
                "height": 8
            },
            {
                "name": "hurt",
                "id": 9,
                "x": 24,
                "y": 64,
                "width": 40,
                "height": 8
            }
        ]
    },
    {
        "name": "texts",
        "entities": [
            {
                "name": "text",
                "id": 0,
                "x": 8,
                "y": 80,
                "width": 8,
                "height": 8,
                "values": {
                    "text": "Press 'C' to Switch",
                    "name": "switch"
                }
            }
        ]
    }
];