export const LEVEL6DATA = [
    {
        "name": "background",
        "tileset": "tiles",
        "data": [
            -1,
            39,
            40,
            41,
            -1,
            39,
            40,
            41,
            -1,
            -1,
            -1,
            30,
            -1,
            -1,
            46,
            -1,
            -1,
            -1,
            46,
            47,
            32,
            50,
            51,
            -1,
            -1,
            -1,
            -1,
            48,
            -1,
            40,
            32,
            37,
            -1,
            56,
            57,
            -1,
            36,
            37,
            30,
            54,
            45,
            46,
            47,
            49,
            48,
            49,
            48,
            32,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            54,
            55,
            54,
            55,
            54,
            55,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            0,
            15,
            1,
            4,
            18,
            19,
            -1,
            -1,
            1,
            1,
            1,
            5,
            7,
            7,
            7,
            8,
            24,
            25,
            24,
            6,
            7,
            7,
            7,
            7,
            12,
            13,
            13,
            14,
            12,
            13,
            14,
            14,
            13,
            13,
            12,
            12,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
        ]
    },
    {
        "name": "collision",
        "entities": [
            {
                "name": "platform",
                "id": 0,
                "x": 0,
                "y": 56,
                "width": 32,
                "height": 8
            },
            {
                "name": "platform",
                "id": 1,
                "x": -8,
                "y": 0,
                "width": 8,
                "height": 72
            },
            {
                "name": "platform",
                "id": 2,
                "x": 96,
                "y": 0,
                "width": 8,
                "height": 72
            },
            {
                "name": "platform",
                "id": 3,
                "x": 56,
                "y": 56,
                "width": 40,
                "height": 8
            }
        ]
    },
    {
        "name": "entities",
        "entities": [
            {
                "name": "player",
                "id": 1,
                "x": 0,
                "y": 48
            },
            {
                "name": "triggerEnemy",
                "id": 2,
                "x": 40,
                "y": 24,
                "width": 8,
                "height": 32,
                "nodes": [
                    {
                        "x": 80,
                        "y": 48
                    }
                ]
            },
            {
                "name": "enemy_mojo",
                "id": 3,
                "x": 80,
                "y": 48,
                "values": {
                    "flipH": 1,
                    "state": "rise",
                    "triggered": true
                }
            },
            {
                "name": "hurt",
                "id": 4,
                "x": 24,
                "y": 64,
                "width": 40,
                "height": 8
            },
            {
                "name": "door",
                "id": 5,
                "x": 88,
                "y": 24,
                "width": 8,
                "height": 32
            },
            {
                "name": "corn_item",
                "id": 6,
                "x": 40,
                "y": 40,
                "width": 8,
                "height": 8
            }
        ]
    },
    {
        "name": "reversers",
        "entities": [
            {
                "name": "reverser",
                "id": 0,
                "x": 48,
                "y": 48,
                "height": 8
            },
            {
                "name": "reverser",
                "id": 1,
                "x": 88,
                "y": 48,
                "height": 8
            }
        ]
    }
];