export const LEVEL5DATA = [
    {
        "name": "background",
        "tileset": "tiles",
        "data": [
            38,
            39,
            37,
            -1,
            -1,
            -1,
            38,
            33,
            -1,
            40,
            -1,
            31,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            45,
            37,
            50,
            51,
            40,
            32,
            -1,
            32,
            38,
            -1,
            45,
            -1,
            38,
            39,
            56,
            57,
            32,
            42,
            43,
            -1,
            44,
            45,
            -1,
            -1,
            44,
            45,
            -1,
            38,
            39,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            44,
            45,
            -1,
            -1,
            -1,
            -1,
            9,
            -1,
            -1,
            -1,
            -1,
            10,
            16,
            11,
            16,
            16,
            1,
            4,
            15,
            15,
            5,
            3,
            1,
            16,
            1,
            5,
            6,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            8,
            12,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            14,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1,
            -1
        ]
    },
    {
        "name": "collision",
        "entities": [
            {
                "name": "platform",
                "id": 0,
                "x": 0,
                "y": 56,
                "width": 96,
                "height": 8
            },
            {
                "name": "platform",
                "id": 1,
                "x": -8,
                "y": 0,
                "width": 8,
                "height": 72
            },
            {
                "name": "platform",
                "id": 2,
                "x": 96,
                "y": 0,
                "width": 8,
                "height": 72
            }
        ]
    },
    {
        "name": "entities",
        "entities": [
            {
                "name": "player",
                "id": 1,
                "x": 8,
                "y": 48
            },
            {
                "name": "triggerEnemy",
                "id": 2,
                "x": 40,
                "y": 24,
                "width": 8,
                "height": 32,
                "nodes": [
                    {
                        "x": 80,
                        "y": 48
                    },
                    {
                        "x": 16,
                        "y": 48
                    }
                ]
            },
            {
                "name": "enemy_mojo",
                "id": 3,
                "x": 80,
                "y": 48,
                "values": {
                    "flipH": 1,
                    "state": "rise",
                    "triggered": true
                }
            },
            {
                "name": "enemy_ryan",
                "id": 4,
                "x": 16,
                "y": 48,
                "values": {
                    "flipH": 1,
                    "state": "rise",
                    "triggered": true
                }
            },
            {
                "name": "door",
                "id": 5,
                "x": 88,
                "y": 24,
                "width": 8,
                "height": 32
            }
        ]
    },
    {
        "name": "reversers",
        "entities": [
            {
                "name": "reverser",
                "id": 0,
                "x": 0,
                "y": 48,
                "height": 8
            },
            {
                "name": "reverser",
                "id": 1,
                "x": 88,
                "y": 48,
                "height": 8
            }
        ]
    }
];